apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity: 
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  value: 