apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        env: 
         - name: MONGO_INITDB_ROOT_USERNAME
           valueFrom: 
              configMapKeyRef:
                name: mongo-user
                key: user_name
         - name: MONGO_INITDB_ROOT_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: my_secret
        ports:
        - containerPort: 27017
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec: 
            command: 
              - cat
              - /etc/localtime 
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}