apiVersion: v1
kind: Service
metadata:
  name: election-service
  labels:
    app: election-ms
spec:
  selector:
    app: election-ms
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: ClusterIP